# Generated by Django 5.0.7 on 2025-04-18 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gymcontrol', '0003_alter_cliente_email_alter_cliente_foto_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suscripcion',
            name='estado',
            field=models.CharField(choices=[('activa', 'Activa'), ('vencida', 'Vencida'), ('pendiente', 'Pendiente')], max_length=10),
        ),
    ]
