# Generated by Django 5.0.7 on 2025-04-23 11:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gymcontrol', '0006_rename_suscripcion_abono_suscripcion'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='abono',
            name='suscripcion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gymcontrol.suscripcion'),
        ),
        migrations.AlterField(
            model_name='suscripcion',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gymcontrol.cliente'),
        ),
        migrations.AlterField(
            model_name='suscripcion',
            name='tipo_pago',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gymcontrol.tipopago'),
        ),
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mensaje', models.TextField()),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('leida', models.BooleanField(default=False)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
