# Generated by Django 5.0.7 on 2025-04-23 12:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gymcontrol', '0007_alter_abono_suscripcion_alter_suscripcion_cliente_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notificacion',
            name='usuario',
        ),
        migrations.AddField(
            model_name='notificacion',
            name='cliente',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='gymcontrol.cliente'),
            preserve_default=False,
        ),
    ]
