# Generated by Django 5.0.7 on 2025-04-23 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gymcontrol', '0008_remove_notificacion_usuario_notificacion_cliente'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notificacion',
            name='cliente',
        ),
    ]
