# Generated by Django 5.0.7 on 2025-04-23 13:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gymcontrol', '0009_remove_notificacion_cliente'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificacion',
            name='cliente',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.CASCADE, to='gymcontrol.cliente'),
            preserve_default=False,
        ),
    ]
